#!/bin/bash
rm -f temp
cat ~/Google\ Drive/Learn/Haskell/AppleContactsParse/ARCHIVE/all.json | jq '.[].fields | select((.ORG != null) and (.ORG[0] | contains("Kasalukuyang")))' | jq -r '. | with_entries(select(.key|match("EMAIL1+";"")))[]' >temp
cat temp
echo `wc -l temp` emails listed
rm -f temp
