#!/bin/bash
rm -f temp
cat ~/Google\ Drive/Learn/Haskell/AppleContactsParse/ARCHIVE/all.json | jq '.[].fields | select((.ORG != null) and (.ORG[0] | contains("Kasalukuyang")))' | jq -r '. | "\(with_entries(select(.key|match("FN+";"")))[]), \(with_entries(select(.key|match("EMAIL1+";"")))[])"' >temp
cat temp
echo `wc -l temp` emails listed
rm -f temp
# From the Web:
# String Interpolation along with the -r option. e.g.
# echo '{ "fmep": { "foo": 112, "bar": 234324, "cat": 21343423 } }' | \
# jq -r '.fmep| "\(.foo) \(.bar)"'
